<a href="https://colab.research.google.com/github/nuhan2007/PyTorch_Practice/blob/pytorch_fundamentals/pytorch_fundamentals_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.6.0+cu124


In [ ]:
scalar = torch.tensor(7) # returns tensor(7)
print(scalar.item()) # returns 7 as Python int
print(scalar.ndim) # number of dimensions = 0

7
0


In [ ]:
#Vector
vector = torch.tensor([7, 7]) # returns tensor([7, 7])
print(vector.ndim) # number of dimensions(square brackets) = 1
print(vector.shape) # = 2 since 2x1 matrix
print(vector[1])

1
torch.Size([2])
tensor(7)


In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
print(MATRIX.ndim) # 2 pairs of square brackets
print(MATRIX.shape) # [2, 2] since 2x2 matrix
print(MATRIX[0])
print(MATRIX[1][1])

2
torch.Size([2, 2])
tensor([7, 8])
tensor(10)


In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0][2])
print(TENSOR[0][2][1])

3
torch.Size([1, 3, 3])
tensor([7, 8, 9])
tensor(8)


In [ ]:
### Random tensors
random_tensor = torch.rand(3, 4) * 10  ### 2 dimensions
random_tensor2 = torch.rand(size = (1, 3, 4)) * 10 ### 3 dimensions
print(random_tensor)
print(random_tensor2)

tensor([[9.4776, 0.4976, 0.5145, 5.4100],
        [2.0606, 9.4142, 5.6589, 9.7219],
        [1.4849, 7.9673, 6.9258, 7.5331]])
tensor([[[8.7576, 3.4762, 2.6401, 9.4444],
         [0.6243, 8.0424, 5.0687, 4.6323],
         [6.2465, 3.8556, 0.9075, 1.0655]]])


In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
ones = torch.ones(size = (3, 4))
print(zeros)
print()
print(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
### Creating a range of tensors
one_to_ten = torch.arange(0, 10) + 1 # or torch.arange(1, 11)
print(one_to_ten) # note: torch.range() may be deprecated soon
print(torch.arange(start = 0, end = 1000, step = 175))

### Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
print(ten_zeros)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([  0, 175, 350, 525, 700, 875])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [ ]:
### Tensor Data Types
### NOTE:: data types 1 of the 3 big errors you'll run into w/ Pytorch DL

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # can use torch.float16 instead
                               device=None, # cpu or gpu?
                               requires_grad=False) # yes/no track gradient?
print(float_32_tensor)
print(float_32_tensor.dtype)

float_16_tensor = float_32_tensor.type(torch.float16) # look up torch.tensor
print(float_16_tensor)
print(float_16_tensor.dtype)

float_16_tensor = float_16_tensor * float_32_tensor
print(float_16_tensor)

tensor([3., 6., 9.])
torch.float32
tensor([3., 6., 9.], dtype=torch.float16)
torch.float16
tensor([ 9., 36., 81.])


In [ ]:
### Getting information (attributes) from tensors
some_tensor = torch.rand(3, 4)
print(f"Datatype of tensor == {some_tensor.dtype}")
some_tensor = some_tensor.type(torch.float16)
print(f"Datatype of tensor == {some_tensor.dtype}")
print(f"Shape of tensor == {some_tensor.shape}")
print(f"Num dimensions of tensor == {some_tensor.ndim}")

Datatype of tensor == torch.float32
Datatype of tensor == torch.float16
Shape of tensor == torch.Size([3, 4])
Num dimensions of tensor == 2


In [ ]:
### Integer Tensors
int_tensor = torch.randint(low = 0, high = 100, size = (3, 4), dtype=torch.int32) # random int tensor
print(int_tensor)

tensor([[39, 75, 53, 80],
        [68,  9, 18, 91],
        [22, 96, 30, 84]], dtype=torch.int32)


In [ ]:
### Tensor Operations
tensor_one = torch.tensor([[1, 2, 3],
                           [5, 9, 4]])

# multiplication (same thing):
result_tensor = tensor_one * 5
result_tensor = torch.mul(tensor_one, 5)

# element-wise
tensor_two = torch.tensor([1, 2, 3])
print(tensor_two, "*", tensor_two)
print(f"equals: {tensor_two * tensor_two}")

# matrix multiplication (1d a bit different)
print(torch.matmul(tensor_two, tensor_two))

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals: tensor([1, 4, 9])
tensor(14)


In [ ]:
#Comparing Runtimes of built-in vs custom functions

%%time
value = 0
for i in range(len(tensor_two)):
  value += tensor_two[i] * tensor_two[i]
value

CPU times: user 477 µs, sys: 74 µs, total: 551 µs
Wall time: 5.59 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor_two, tensor_two)

CPU times: user 60 µs, sys: 9 µs, total: 69 µs
Wall time: 72.2 µs


tensor(14)

In [ ]:
### NOTE:: shape is another one of the 3 big errors you'll run into w/ Pytorch
### Matrix multiplication (not 1d):

## Rules: inner dims must match --- outer dims = result matrix dims
tensor1 = torch.rand(3, 2)
tensor2 = torch.rand(2, 4)
result_tensor = torch.matmul(tensor1, tensor2)
## since 2 == 2, 3x3 result matrix

print(result_tensor)

tensor1 = torch.tensor([[1 ,2],
                        [3, 4],
                        [5, 6]])
tensor2 = torch.tensor([[7, 8],
                        [9, 10],
                        [11, 12]])
# 2 != 3...
# to multiply we need a TRANSPOSE: swapping axes of a tensor
print(tensor2.T)
result_tensor = torch.matmul(tensor1, tensor2.T)
print(result_tensor)


tensor([[0.6339, 0.9827, 0.5883, 0.9454],
        [0.5363, 0.9964, 0.6251, 1.0491],
        [0.7346, 0.7138, 0.3536, 0.4537]])
tensor([[ 7,  9, 11],
        [ 8, 10, 12]])
tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])


In [ ]:
### TENSOR aggregation (mins, maxes, sums, means, etc)
x = torch.arange(15, 100, 10)
print(f"torch.max(x) == {torch.max(x)} is the same as x.max() == {x.max()}" )

print(f"torch.mean(x) error bc Long type --> torch.mean(x.type(torch.float32)) == {torch.mean(x.type(torch.float32))}")
print(f"same with x.mean() --> x.type(torch.float32).mean() == {x.type(torch.float32).mean()}")
print(torch.sum(x), "==", x.sum())

torch.max(x) == 95 is the same as x.max() == 95
torch.mean(x) error bc Long type --> torch.mean(x.type(torch.float32)) == 55.0
same with x.mean() --> x.type(torch.float32).mean() == 55.0
tensor(495) == tensor(495)


In [ ]:
### Find positional min/max/etc in tensors
minPos = x.argmin()
maxPos = x.argmax()
print(minPos, maxPos)

tensor(0) tensor(8)


In [4]:
# TENSOR Transformations

x = torch.arange(1., 10.)

# Reshaping
mod_x = x.reshape(1,9)
print(mod_x)
mod_x = x.reshape(3, 3)
print(mod_x, "\n")

# Change view
z = x.view(3, 3)
z[0][0] = 100 ### Shares same reference, changes x too
print(x)
print(z, "\n")

# Stacking tensors
mod_x = x.flip(0)
x_stacked = torch.stack([x, mod_x, x * 5], dim = 0)
print(x_stacked, "\n")

sqeezed_x = x.squeeze() # removes all 1-dimensions
unsqueezed_x = x.unsqueeze(dim = 0) # adds a 1-dim in specified dimension

x = torch.rand(2, 3, 5)
mod_x = torch.permute(x, (2, 0, 1)) # rearrange dimensions (0-indexedly)
# permute is also something used frequently with images
print(x.size(), "\n", x, "\n")
print(mod_x.size(), "\n", mod_x)
# changing a value in x changes the values in mod_x


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 

tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.])
tensor([[100.,   2.,   3.],
        [  4.,   5.,   6.],
        [  7.,   8.,   9.]]) 

tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [  9.,   8.,   7.,   6.,   5.,   4.,   3.,   2., 100.],
        [500.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.]]) 

torch.Size([2, 3, 5]) 
 tensor([[[0.8301, 0.1948, 0.0432, 0.7437, 0.3911],
         [0.1767, 0.3142, 0.3422, 0.9949, 0.2956],
         [0.8004, 0.1709, 0.1516, 0.0172, 0.5776]],

        [[0.3735, 0.8127, 0.5766, 0.3276, 0.1958],
         [0.9937, 0.7575, 0.6647, 0.4432, 0.6203],
         [0.8770, 0.0027, 0.1879, 0.4088, 0.1732]]]) 

torch.Size([5, 2, 3]) 
 tensor([[[0.8301, 0.1767, 0.8004],
         [0.3735, 0.9937, 0.8770]],

        [[0.1948, 0.3142, 0.1709],
         [0.8127, 0.7575, 0.0027]],

        [[0.0432, 0.3422, 0.1516],


In [ ]:
### Indexing with tensors
# (:) == slicing, -num == len(arr) - num == starting from end
x = torch.arange(1, 19).reshape(2, 3, 3)
print(x)
print(x[:, :, 2])


tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
tensor([[ 3,  6,  9],
        [12, 15, 18]])
